import { APP_CONFIG } from '../config/app.config.js';
import { createKey, getValue, removeValue, setValue, updateValue } from './db.service.js';
function toBase64(bytes){let binary='';const step=0x8000;for(let i=0;i<bytes.length;i+=step)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+step,bytes.length)));return btoa(binary);}
function fromBase64(value){const binary=atob(value),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes;}
async function checkSignature(file){const ext=file.name.split('.').pop()?.toLowerCase()||'';const head=new Uint8Array(await file.slice(0,8).arrayBuffer());if(ext==='pdf'&&String.fromCharCode(...head.slice(0,4))!=='%PDF')throw new Error('The selected file is not a valid PDF.');if(ext==='docx'&&!(head[0]===0x50&&head[1]===0x4b))throw new Error('The selected file is not a valid DOCX.');}
export async function validateThesisFile(file){if(!(file instanceof File))throw new Error('Select a manuscript file.');if(file.size<=0)throw new Error('The selected file is empty.');if(file.size>APP_CONFIG.maxFileSizeBytes)throw new Error('The manuscript must not exceed 10 MB.');const ext=file.name.split('.').pop()?.toLowerCase()||'';if(!APP_CONFIG.acceptedExtensions.includes(ext))throw new Error('Only PDF and DOCX files are accepted.');await checkSignature(file);return true;}
export async function uploadFileToRealtimeDatabase(file,{ownerUid,thesisId,onProgress=()=>{}}){await validateThesisFile(file);const fileId=createKey('files'),chunkCount=Math.ceil(file.size/APP_CONFIG.fileChunkBytes);const metadata={ownerUid,thesisId,name:file.name,type:file.type||'application/octet-stream',size:file.size,chunkCount,status:'uploading',published:false,createdAt:Date.now()};await setValue(`files/${fileId}`,metadata);try{for(let i=0;i<chunkCount;i++){const start=i*APP_CONFIG.fileChunkBytes,end=Math.min(start+APP_CONFIG.fileChunkBytes,file.size);const bytes=new Uint8Array(await file.slice(start,end).arrayBuffer());await setValue(`fileChunks/${fileId}/${String(i).padStart(5,'0')}`,toBase64(bytes));onProgress(Math.round(((i+1)/chunkCount)*100));}await updateValue(`files/${fileId}`,{status:'ready',completedAt:Date.now()});return{fileId,...metadata,status:'ready'};}catch(error){await updateValue(`files/${fileId}`,{status:'failed',failedAt:Date.now()}).catch(()=>{});throw error;}}
export async function getFileMetadata(fileId){return getValue(`files/${fileId}`);}
export async function reconstructFile(fileId){const metadata=await getFileMetadata(fileId);if(!metadata)throw new Error('File metadata was not found.');if(metadata.status!=='ready')throw new Error('The file is not ready.');const chunks=await getValue(`fileChunks/${fileId}`);if(!chunks)throw new Error('The manuscript data is missing.');const ordered=Object.keys(chunks).sort().map(k=>fromBase64(chunks[k]));return{metadata,blob:new Blob(ordered,{type:metadata.type||'application/octet-stream'})};}
export async function deleteRealtimeFile(fileId){await Promise.all([removeValue(`fileChunks/${fileId}`),removeValue(`files/${fileId}`)]);}
