import { getThesis, getSubmissionHistory, resubmitThesis } from '../../services/thesis.service.js';
import { getReviews } from '../../services/review.service.js';
import { reconstructFile } from '../../services/file.service.js';
import { downloadBlob } from '../../utils/file.js';
import { pageHeader, statusBadge, infoRow, emptyState } from '../../components/ui.js';
import { escapeHtml, formDataObject, setButtonLoading } from '../../utils/dom.js';
import { formatDateTime } from '../../utils/date.js';
import { toast } from '../../components/toast.js';
import { icon } from '../../components/icons.js';
export async function render({profile,params}){const t=await getThesis(params.id);if(!t||t.ownerUid!==profile.uid)return emptyState('Thesis not found','The record does not exist or you do not have permission to view it.','<a class="btn btn-secondary" href="#/student/theses">Back</a>');const[reviews,history]=await Promise.all([getReviews(t.id),getSubmissionHistory(t.id)]);return `${pageHeader(t.title,'Detailed manuscript workflow and adviser feedback.',`<button class="btn btn-secondary" id="download-current" data-file="${escapeHtml(t.currentFileId||'')}">${icon('download')} Download current file</button>`)}<div class="detail-grid"><section class="panel"><div class="panel-header"><div><h2>Thesis record</h2>${statusBadge(t.status)}</div></div><div class="panel-body"><div class="info-list">${infoRow('Authors',t.authors||t.studentName)}${infoRow('Program',t.program)}${infoRow('Adviser',t.adviserName||'Unassigned')}${infoRow('Academic Year',t.academicYear)}${infoRow('Version',String(t.version||1))}${infoRow('Last updated',formatDateTime(t.updatedAt))}</div><div class="content-section"><h3>Abstract</h3><p class="long-copy">${escapeHtml(t.abstract||'—')}</p></div><div class="content-section"><h3>Keywords</h3><p>${escapeHtml(t.keywords||'—')}</p></div></div></section><aside class="panel"><div class="panel-header"><h2>Review feedback</h2></div><div class="panel-body timeline">${reviews.length?reviews.map(r=>`<article class="timeline-item"><div class="timeline-dot"></div><div><div class="timeline-head"><strong>${escapeHtml(r.adviserName||'Adviser')}</strong>${statusBadge(r.decision)}</div><p>${escapeHtml(r.comment)}</p><small>${formatDateTime(r.createdAt)}</small></div></article>`).join(''):emptyState('No reviews yet','Adviser feedback will appear here.')}</div></aside></div>${t.status==='revision_required'?`<section class="panel form-panel"><div class="panel-header"><h2>Submit revised manuscript</h2></div><div class="panel-body"><form id="resubmit-form" class="form-stack"><label class="field"><span>Revised PDF or DOCX</span><input id="revision-file" type="file" accept=".pdf,.docx" required></label><label class="field"><span>Revision note</span><textarea name="note" rows="3" required></textarea></label><div class="upload-progress" id="upload-progress" hidden><div><span>Uploading revision</span><strong id="upload-percent">0%</strong></div><div class="progress-track"><span id="progress-bar"></span></div></div><button class="btn btn-primary" type="submit">Submit revision</button></form></div></section>`:''}<section class="panel"><div class="panel-header"><h2>Submission history</h2></div><div class="panel-body timeline">${history.length?history.map(h=>`<article class="timeline-item"><div class="timeline-dot"></div><div><strong>Version ${h.version}</strong><p>${escapeHtml(h.note||'No submission note.')}</p><small>${formatDateTime(h.submittedAt)}</small></div></article>`).join(''):''}</div></section>`;}
export function mount({profile,params}){document.getElementById('download-current')?.addEventListener('click',e=>download(e.currentTarget));document.getElementById('resubmit-form')?.addEventListener('submit',async e=>{e.preventDefault();const file=document.getElementById('revision-file').files[0],btn=e.currentTarget.querySelector('button'),wrap=document.getElementById('upload-progress'),pct=document.getElementById('upload-percent'),bar=document.getElementById('progress-bar');setButtonLoading(btn,true,'Uploading...');wrap.hidden=false;try{await resubmitThesis(profile,params.id,file,formDataObject(e.currentTarget).note,p=>{pct.textContent=`${p}%`;bar.style.width=`${p}%`;});toast('Revision submitted.','success');location.hash=`#/student/thesis/${params.id}?refresh=${Date.now()}`;}catch(err){toast(err.message,'error');}finally{setButtonLoading(btn,false);}});}
async function download(btn){btn.disabled=true;try{const{metadata,blob}=await reconstructFile(btn.dataset.file);downloadBlob(blob,metadata.name||'manuscript');}catch(err){toast(err.message,'error');}finally{btn.disabled=false;}}
